# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'face.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nface.proto\x12\x04\x66\x61\x63\x65\"\x07\n\x05\x45mpty\")\n\x13RecognitionResponse\x12\x12\n\nstudent_id\x18\x01 \x01(\t2M\n\x0b\x46\x61\x63\x65Service\x12>\n\x12StreamRecognitions\x12\x0b.face.Empty\x1a\x19.face.RecognitionResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_RECOGNITIONRESPONSE']._serialized_start=29
  _globals['_RECOGNITIONRESPONSE']._serialized_end=70
  _globals['_FACESERVICE']._serialized_start=72
  _globals['_FACESERVICE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
